### ISSUE TITLE
type 'String' is not a subtype of type 'Map<dynamic, dynamic>' in type cast

### ISSUE THREAD

**Issue by zenkog** [tekartik/sembast.dart#208]
This is an intermittent problem. Everything seems fine but sometimes it gives this error. I do not know how to persistently reproduce this error.

This is the code to store the data in the database:
```
final studioItem = ItemDB(
          lastUpdated: Timestamp.now(), // Firestore Timestamp
          dateCreated: Timestamp.now(), // Firestore Timestamp
          visibleColorMap: visibleColorMap,
          shapesString: newShapesString,
          linesString: newLinesString,
          artID: id,
          category: category,
        );

await storeRef.record(itemKey).put(db, ItemDB.toMap());
```

Then I have a listener defined like this:
```
Stream<List<RecordSnapshot<String, Map<String, dynamic>>>> _recordStream;
_recordStream = storeRef
        .query(finder: finder)
        .onSnapshots(db);
```

Which later on the _recordStream is being put into a StreamBuilder like this:
```
StreamBuilder<List<RecordSnapshot<String, Map<String, dynamic>>>>(
          initialData: [],
          stream: _recordStream,
          builder: (context, snapshot) {
         switch (snapshot.connectionState) {
              case ConnectionState.none:
              case ConnectionState.waiting:
                return _onLoadingDataState();
                break;
              case ConnectionState.active:
                if (snapshot.hasError) {
                  final message = snapshot.error.toString(); 
                  print('Error in StudioPage: $message'); // THIS PRINTS: type 'String' is not a subtype of type 'Map<dynamic, dynamic>' in type cast
                }
                if (snapshot.hasData)
                  return _onDataReady(ItemDB.fromRecordSnapshots(snapshot.data));
                else
                  return _onLoadingDataState();

                break;
              case ConnectionState.done:
                return _onDataReady(ItemDB.fromRecordSnapshots(snapshot.data),
                    isEof: true, isLoading: false);
                break;
            }
            return _onLoadingDataState();
          }),

```

Note: Once again this is an intermittent problem. It does not always happen.
Also there is no other place in my code that I write into this key. So somehow the data was transformed into String and failed in the process even before it reached my Stream variable.

I'm using the adaptor for Sembast Timestamp to Firestore Timestamp. Here is my `pubspec.yaml`:
```
  sembast: ^2.4.7+5
  sembast_cloud_firestore_type_adapters:
    git:
      url: git://github.com/tekartik/sembast_flutter_more.dart
      path: cloud_firestore_type_adapters
      ref: dart2
      version: '>=0.1.0'
```

And here is my `flutter doctor`
```
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Mac OS X 10.15.6 19G73, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.47.3)
[✓] Connected device (4 available)

• No issues found!
```

**Comment by zenkog** [comment]
I found the problem. It is because of the `sortOrder`.

It was trying to sort a Timestamp object. That is why it failed. 

I guess I just need to convert all Timestamp into int.

**Comment by alextekartik** [comment]
I added a small unit test about Timestamp sorting here: https://github.com/tekartik/sembast_flutter_more.dart/blob/master/cloud_firestore_type_adapters/test/timestamp_order_test.dart

Make sure you open the database with the correct codec (and maybe old data will have a bad format then causing the issue) since the beginning.

**Comment by zenkog** [comment]
Please pardon me.. I just got the error again even after changing Timestamp to microseconds. Really strange. It is truly intermittent. Even after the app being deleted and reinstalled. Sometimes works, sometimes not. I don't know how to find the cause. Is it a memory leak? But I have checked every single controllers and streams and they are all closed it properly.

About the codec. This is what I got in my pubspec.yaml, is this the right one?

```
  sembast: ^2.4.7+6
  sembast_cloud_firestore_type_adapters:
    git:
      url: git://github.com/tekartik/sembast_flutter_more.dart
      path: cloud_firestore_type_adapters
      ref: dart2
      version: '>=0.1.0'
```
